### ISSUE TITLE
Python 3 issue with `html` dependency?

### ISSUE THREAD

**Issue by robintw** [j-towns/iprofiler#2]
When trying to install this I get the following error:

```
Collecting html
  Using cached html-1.16.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-2bd7qzxh/html/setup.py", line 12, in <module>
        long_description = __doc__.decode('utf8'),
    AttributeError: 'str' object has no attribute 'decode'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-2bd7qzxh/html
```

This looks like a Python 2 / Python 3 compatibility error from the `html` module, but I can't find a relevant Github repo to report this to the `html` author. You said in the readme that you'd tested it on Python 3 - did you find a workaround for this issue?

**Comment by j-towns** [comment]
Thanks for raising this. Should hopefully be fixed by the latest commit (made earlier today)

**Comment by robintw** [comment]
Perfect, that fixed it :-)

**Comment by ericmdefeo** [comment]
I'm having this same error today. How was it solved before? Thank you!

**Comment by rausm** [comment]
Until someone fixes the [html] package (next version comes out), download the archive locally from pypi, unpack, edit setup.py, remove the .decode(...) call and run 'setup.py build install' (sprinkle with sudo, ./ or python as/if neccessary ;-), or just include the file in your project (the module is python 3 compatible, it's just setup that's python 3 incompatible)

**Comment by j-towns** [comment]
You shouldn't need the html package to run iprofiler. It is no longer a
dependency.

**Comment by Petesta** [comment]
Is this still an issue for other people? I tried installing `html` for Python 3.6 and I'm receiving this error. The library installs for Python 2.7.

```shell
Petesta :: λ -> ~/random pip3 install html
The directory '/Users/Petesta/Library/Caches/pip/http' or its parent directory is not owned by the current user and the cache has been disabled. Please check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
The directory '/Users/Petesta/Library/Caches/pip' or its parent directory is not owned by the current user and caching wheels has been disabled. check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting html
  Downloading html-1.16.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-build-ihz2hz6i/html/setup.py", line 12, in <module>
        long_description = __doc__.decode('utf8'),
    AttributeError: 'str' object has no attribute 'decode'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-build-ihz2hz6i/html/
```
