### ISSUE TITLE
Pandas is  a dependency

### ISSUE THREAD

**Issue by Fazel94** [j-towns/iprofiler#4]
When I try to run the %load_ext iprofiler after installation it gives me the following error:
RuntimeError: The bokeh.charts interface requires Pandas (http://pandas.pydata.org) to be installed.

 But in the time of installation there were no mention of pandas, please add pandas as dependency.

**Comment by j-towns** [comment]
Hi, thanks for raising this. Luckily that was caused by an import that I didn't actually need, should be fixed by the commit I just made.

J
