### ISSUE TITLE
%iprofile command doesn't output anything

### ISSUE THREAD

**Issue by Fazel94** [j-towns/iprofiler#5]
I executed following commands in my jupyter 4.2 notebook and just saw regular output and nothing else:

> %iprofile 10_10
> def foo(i):
>     for j in range(i):
>         for k in range(j):
>             print i_j*k
> %iprofile  foo(10)

**Comment by j-towns** [comment]
Thanks for raising. Can you make sure you have the latest ipywidgets installed by running:

```
pip install --upgrade ipywidgets
```

Which web browser are you running? Open the browser's console and see whether anything appears there when you run `%iprofiler foo(10)`.

**Comment by j-towns** [comment]
You should be seeing something like this:
![untitled](https://cloud.githubusercontent.com/assets/15261883/15647240/48600e04-265a-11e6-9c55-55c91bfb6517.png)

**Comment by Fazel94** [comment]
I see this :smile: 
![screenshot from 2016-05-30 15 11 16](https://cloud.githubusercontent.com/assets/7665589/15647476/09e33a9c-2679-11e6-86d7-4ab30d12fdff.png)
although without the first call of the foo it doesn't change and add a table

**Comment by j-towns** [comment]
Can you look at your browser's console (on Firefox this is under Tools -> Web Developer -> Web Console) and see if anything is appearing there when you run `%iprofile foo`.

**Comment by j-towns** [comment]
Also can you point your web browser to `http://localhost:8888/nbextensions/iprofiler/iprofiler.js` while Jupyter is running. If you get 404 Not Found then the javascript for the widget hasn't installed correctly. You can install it manually by opening a Python interpreter in the iprofiler directory and running

```
import notebook.nbextensions
notebook.nbextensions.install_nbextension('./js/iprofiler', user=True)
```

**Comment by Fazel94** [comment]
The url returns correctly. :disappointed:

**Comment by j-towns** [comment]
OK, well it's quite hard for me to know what is going on. If you are able to [look at your browser's console](#issuecomment-222466462) too that might help.

Although the js seems to have installed into the right place I still think the problem is most likely with the installation process, which is currently very hacky. Jupyter recently published a repo demonstrating best practices for widget packaging/distribution and I need to update iprofiler to bring it in line with these. I will write on here when I do that.

**Comment by j-towns** [comment]
OK I've made some changes which I hope will fix the problem. Can you uninstall iprofiler by running

```
pip uninstall iprofiler
```

and then reinstall using the new instructions in the readme.
